/**
 * Reads proballers-stats-2026.json + nba-rosters-2026.json and emits
 * src/data/proballersRatings.ts with per-slot profiles aligned to parody roster order.
 *
 * Slot index 0 = first player in nba-rosters-2026.json for that team (matches parodyRoster.ts).
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { reorderRosterByStars } from './team-star-order.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROBALLERS = join(__dirname, 'proballers-stats-2026.json');
const NBA_ROSTERS = join(__dirname, 'nba-rosters-2026.json');
const OUTPUT = join(__dirname, '../src/data/proballersRatings.ts');
const ROSTER_SIZE = 18;

const proballers = JSON.parse(readFileSync(PROBALLERS, 'utf-8'));
const nbaRosters = JSON.parse(readFileSync(NBA_ROSTERS, 'utf-8'));

function clamp(n, lo, hi) {
  return Math.max(lo, Math.min(hi, n));
}

function normName(name) {
  return name
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z]/g, '');
}

function lastToken(name) {
  const parts = name.trim().split(/\s+/);
  return normName(parts[parts.length - 1] ?? name);
}

function matchProballersPlayer(nbaName, pbPlayers, used) {
  const nNorm = normName(nbaName);
  const nLast = lastToken(nbaName);
  const nFirst = normName(nbaName.split(/\s+/)[0] ?? '');

  const candidates = pbPlayers.filter((p) => !used.has(p.name));

  let found = candidates.find((p) => normName(p.name) === nNorm);
  if (found) return found;

  found = candidates.find((p) => {
    const pNorm = normName(p.name);
    const pLast = lastToken(p.name);
    return pLast === nLast || pNorm.includes(nLast) || nNorm.includes(pLast);
  });
  if (found) return found;

  found = candidates.find((p) => {
    const parts = p.name.split(/\s+/);
    const pFirst = normName(parts[0] ?? '');
    const pLast = lastToken(p.name);
    return pFirst === nFirst && (pLast === nLast || pLast.startsWith(nLast) || nLast.startsWith(pLast));
  });
  return found ?? null;
}

function statsToOverall(ppg, rpg, apg, mpg, games) {
  const gamesWeight = Math.min(games, 60) / 60;
  const composite = ppg + rpg * 0.4 + apg * 0.5;
  const mpgFactor = Math.min(mpg, 38) / 38;
  const raw = composite * mpgFactor * (0.75 + 0.25 * gamesWeight);
  return clamp(Math.round(62 + (raw - 2) * (32 / 28)), 62, 94);
}

function statsToPotential(overall, age) {
  if (age >= 33) return overall;
  const bonus = Math.max(0, 27 - age);
  return clamp(overall + bonus + 2, overall, 94);
}

const FALLBACK = {
  heightInches: 78,
  age: 24,
  ppg: 6,
  rpg: 2,
  apg: 1.5,
  games: 40,
  mpg: 12,
};

function toSlotProfile(raw) {
  const ppg = raw.ppg ?? FALLBACK.ppg;
  const rpg = raw.rpg ?? FALLBACK.rpg;
  const apg = raw.apg ?? FALLBACK.apg;
  const mpg = raw.mpg ?? FALLBACK.mpg;
  const games = raw.games ?? FALLBACK.games;
  const age = raw.age ?? FALLBACK.age;
  const overall = statsToOverall(ppg, rpg, apg, mpg, games);
  return {
    overall,
    potential: statsToPotential(overall, age),
    age,
    mpg: Math.round(mpg * 10) / 10,
    heightInches: raw.heightInches ?? FALLBACK.heightInches,
    seasonStats: {
      ppg: Math.round(ppg * 10) / 10,
      rpg: Math.round(rpg * 10) / 10,
      apg: Math.round(apg * 10) / 10,
      games,
      mpg: Math.round(mpg * 10) / 10,
    },
  };
}

const ratings = {};
const matchLog = { matched: 0, fallback: 0 };

for (const [key, roster] of Object.entries(nbaRosters)) {
  const orderedRoster = reorderRosterByStars(key, roster);
  const pbPlayers = proballers[key] ?? [];
  const used = new Set();
  const slots = orderedRoster.slice(0, ROSTER_SIZE).map((entry) => {
    const match = matchProballersPlayer(entry.name, pbPlayers, used);
    if (match) {
      used.add(match.name);
      matchLog.matched += 1;
      return toSlotProfile(match);
    }
    matchLog.fallback += 1;
    return toSlotProfile(FALLBACK);
  });

  while (slots.length < ROSTER_SIZE) {
    matchLog.fallback += 1;
    slots.push(toSlotProfile(FALLBACK));
  }

  ratings[key] = slots;
}

const lines = [
  '// AUTO-GENERATED by scripts/compute-ratings.mjs — do not edit manually.',
  '// Source: scripts/proballers-stats-2026.json aligned to scripts/nba-rosters-2026.json slot order.',
  '',
  'import type { PlayerSeasonStats } from \'../types/game\';',
  '',
  'export type SlotRating = {',
  '  overall: number;',
  '  potential: number;',
  '  age: number;',
  '  mpg: number;',
  '  heightInches: number;',
  '  seasonStats: PlayerSeasonStats;',
  '};',
  '',
  '/** Per-team roster-slot profiles (0–17) aligned with parodyRoster.ts order. */',
  'export const PROBALLERS_RATINGS: Record<string, SlotRating[]> = {',
];

for (const [key, slots] of Object.entries(ratings)) {
  lines.push(`  '${key}': [`);
  for (const s of slots) {
    const st = s.seasonStats;
    lines.push(
      `    { overall: ${s.overall}, potential: ${s.potential}, age: ${s.age}, mpg: ${s.mpg}, heightInches: ${s.heightInches}, seasonStats: { ppg: ${st.ppg}, rpg: ${st.rpg}, apg: ${st.apg}, games: ${st.games}, mpg: ${st.mpg} } },`,
    );
  }
  lines.push('  ],');
}

lines.push('};');
lines.push('');

writeFileSync(OUTPUT, lines.join('\n'), 'utf-8');
console.log(`Written: ${OUTPUT}`);
console.log(`Matched ${matchLog.matched} roster slots; ${matchLog.fallback} fallbacks.`);

console.log('\nSanity check — LA teams slot 0:');
for (const key of ['LA|Cosmos', 'LA|Current']) {
  const s = ratings[key]?.[0];
  if (s) console.log(`  ${key}: ovr=${s.overall}  ppg=${s.seasonStats.ppg}  age=${s.age}`);
}
